In [2]:
import os
import pandas as pd
import numpy as np
os.chdir('C:\\Users\\kunjeshparekh\\Desktop\\KP\\IMS\\py\\project\\JobaThon_AV')

In [3]:
train=pd.read_csv("train_Df64byy.csv")
test=pd.read_csv("test_YCcRUnU.csv")

In [4]:
train.info()
test.info()
train.columns[:-1]==test.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       50882 non-null  int64
 1   City_Code                50882 non-null  object
 2   Region_Code              50882 non-null  int64
 3   Accomodation_Type        50882 non-null  object
 4   Reco_Insurance_Type      50882 non-null  object
 5   Upper_Age                50882 non-null  int64
 6   Lower_Age                50882 non-null  int64
 7   Is_Spouse                50882 non-null  object
 8   Health Indicator         39191 non-null  object
 9   Holding_Policy_Duration  30631 non-null  object
 10  Holding_Policy_Type      30631 non-null  float64
 11  Reco_Policy_Cat          50882 non-null  int64
 12  Reco_Policy_Premium      50882 non-null  float64
 13  Response                 50882 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 5.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21805 entries, 0 to 21804
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       21805 non-null  int64
 1   City_Code                21805 non-null  object
 2   Region_Code              21805 non-null  int64
 3   Accomodation_Type        21805 non-null  object
 4   Reco_Insurance_Type      21805 non-null  object
 5   Upper_Age                21805 non-null  int64
 6   Lower_Age                21805 non-null  int64
 7   Is_Spouse                21805 non-null  object
 8   Health Indicator         16778 non-null  object
 9   Holding_Policy_Duration  13202 non-null  object
 10  Holding_Policy_Type      13202 non-null  float64
 11  Reco_Policy_Cat          21805 non-null  int64
 12  Reco_Policy_Premium      21805 non-null  float64
dtypes: float64(2), int64(5), object(6)
memory usage: 2.2+ MB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [5]:
train.isna().sum()

ID                             0
City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health Indicator           11691
Holding_Policy_Duration    20251
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64

In [6]:
train["Health Indicator"][train["Health Indicator"].isna()]="X10" #Filled NAs 
test["Health Indicator"][test["Health Indicator"].isna()]="X10" #Filled NAs 
train["Holding_Policy_Type"][train["Holding_Policy_Type"].isna()]="Unavailable" #Filled NAs 
test["Holding_Policy_Type"][test["Holding_Policy_Type"].isna()]="Unavailable" #Filled NAs 
train["Holding_Policy_Duration"][train["Holding_Policy_Duration"]=='14+']=20
train["Holding_Policy_Duration"][train["Holding_Policy_Duration"].isna()]=0
test["Holding_Policy_Duration"][test["Holding_Policy_Duration"]=='14+']=20
test["Holding_Policy_Duration"][test["Holding_Policy_Duration"].isna()]=0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
train["Health Indicator"].unique()
train["Holding_Policy_Type"].unique()
train["Holding_Policy_Duration"].unique()

array([20, 0, '1.0', '3.0', '5.0', '9.0', '14.0', '7.0', '2.0', '11.0',
       '10.0', '8.0', '6.0', '4.0', '13.0', '12.0'], dtype=object)

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns
train.corr()

,ID,Region_Code,Upper_Age,Lower_Age,Reco_Policy_Cat,Reco_Policy_Premium,Response
ID,1.000000,-0.000465,-0.001725,0.001101,-0.002235,-0.002350,0.005159
Region_Code,-0.000465,1.000000,-0.005649,-0.005928,-0.065120,-0.010797,0.001121
Upper_Age,-0.001725,-0.005649,1.000000,0.921392,0.025257,0.792689,0.002772
Lower_Age,0.001101,-0.005928,0.921392,1.000000,0.021163,0.615739,-0.002099
Reco_Policy_Cat,-0.002235,-0.065120,0.025257,0.021163,1.000000,0.060989,0.114321
Reco_Policy_Premium,-0.002350,-0.010797,0.792689,0.615739,0.060989,1.000000,0.007943
Response,0.005159,0.001121,0.002772,-0.002099,0.114321,0.007943,1.000000

In [10]:
train.head()
#train.Response.value_counts()

,ID,City_Code,Region_Code,Accomodation_Type,Reco_Insurance_Type,Upper_Age,Lower_Age,Is_Spouse,Health Indicator,Holding_Policy_Duration,Holding_Policy_Type,Reco_Policy_Cat,Reco_Policy_Premium,Response
0,1,C3,3213,Rented,Individual,36,36,No,X1,20,3,22,11628.0,0
1,2,C5,1117,Owned,Joint,75,22,No,X2,0,Unavailable,22,30510.0,0
2,3,C5,3732,Owned,Individual,32,32,No,X10,1.0,1,19,7450.0,1
3,4,C24,4378,Owned,Joint,52,48,No,X1,20,3,19,17780.0,0
4,5,C8,2190,Rented,Individual,44,44,No,X2,3.0,1,16,10404.0,0

In [11]:
cat=['City_Code','Accomodation_Type','Reco_Insurance_Type','Is_Spouse','Health Indicator','Holding_Policy_Type','Reco_Policy_Cat']
num=['Region_Code','Upper_Age','Lower_Age','Holding_Policy_Duration','Reco_Policy_Premium']

In [12]:
train_c=train[cat]
train_n=train[num]

In [13]:
train_c['Reco_Policy_Cat']=train_c['Reco_Policy_Cat'].astype('str')
train_n['Holding_Policy_Duration']=train_n['Holding_Policy_Duration'].astype('float')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
test_c=test[cat]
test_n=test[num]

In [15]:
test_c['Reco_Policy_Cat']=test_c['Reco_Policy_Cat'].astype('str')
test_n['Holding_Policy_Duration']=test_n['Holding_Policy_Duration'].astype('float')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
pd.get_dummies(train_c,drop_first=True)

,City_Code_C10,City_Code_C11,City_Code_C12,City_Code_C13,City_Code_C14,City_Code_C15,City_Code_C16,City_Code_C17,City_Code_C18,City_Code_C19,...,Reco_Policy_Cat_20,Reco_Policy_Cat_21,Reco_Policy_Cat_22,Reco_Policy_Cat_3,Reco_Policy_Cat_4,Reco_Policy_Cat_5,Reco_Policy_Cat_6,Reco_Policy_Cat_7,Reco_Policy_Cat_8,Reco_Policy_Cat_9
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50877,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50878,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
50879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50880,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50881,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
train_c1=pd.get_dummies(train_c,drop_first=True)
test_c1=pd.get_dummies(test_c,drop_first=True)

In [18]:
train_final=pd.concat([train_n,train_c1],axis=1)
test_final=pd.concat([test_n,test_c1],axis=1)

In [19]:
test_final.head()

,Region_Code,Upper_Age,Lower_Age,Holding_Policy_Duration,Reco_Policy_Premium,City_Code_C10,City_Code_C11,City_Code_C12,City_Code_C13,City_Code_C14,...,Reco_Policy_Cat_20,Reco_Policy_Cat_21,Reco_Policy_Cat_22,Reco_Policy_Cat_3,Reco_Policy_Cat_4,Reco_Policy_Cat_5,Reco_Policy_Cat_6,Reco_Policy_Cat_7,Reco_Policy_Cat_8,Reco_Policy_Cat_9
0,156,30,30,6.0,11934.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,7,69,68,3.0,32204.8,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,564,28,28,2.0,9240.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1177,23,23,3.0,9086.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,951,75,75,0.0,22534.0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [20]:
train_final.head()

,Region_Code,Upper_Age,Lower_Age,Holding_Policy_Duration,Reco_Policy_Premium,City_Code_C10,City_Code_C11,City_Code_C12,City_Code_C13,City_Code_C14,...,Reco_Policy_Cat_20,Reco_Policy_Cat_21,Reco_Policy_Cat_22,Reco_Policy_Cat_3,Reco_Policy_Cat_4,Reco_Policy_Cat_5,Reco_Policy_Cat_6,Reco_Policy_Cat_7,Reco_Policy_Cat_8,Reco_Policy_Cat_9
0,3213,36,36,20.0,11628.0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,1117,75,22,0.0,30510.0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,3732,32,32,1.0,7450.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4378,52,48,20.0,17780.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2190,44,44,3.0,10404.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
train.Response.value_counts()

0    38673
1    12209
Name: Response, dtype: int64

In [73]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(class_weight="balanced")    
lr.fit(train_final,train.Response)
preds=lr.predict_proba(test_final)

In [88]:
train_final=(train_final-train_final.mean())/train_final.std()
test_final=(test_final-test_final.mean())/test_final.std()

import xgboost as xgb
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error
xg_reg = xgb.XGBRegressor(objective ='binary:logistic', colsample_bytree = 0.6, learning_rate = 0.1,
                max_depth = 6, alpha = 0.1, n_estimators = 1000) #colsample_bytree = 0.4, learning_rate = 0.075
#xg_reg.fit(X_train,y_train)
xg_reg.fit(train_final,train.Response)
print(roc_auc_score(train.Response, xg_reg.predict(train_final)))
preds = xg_reg.predict(test_final)

0.9171722980819983

In [103]:
train_final=(train_final-train_final.mean())/train_final.std()
test_final=(test_final-test_final.mean())/test_final.std()

train_final1=pd.concat([train_final,train_final[train.Response==1].reset_index().iloc[:,1:],train_final[train.Response==1].reset_index().iloc[:,1:]],axis=0)
resp=pd.concat([train.Response,pd.DataFrame(np.ones(len(train_final1)-len(train.Response)))],axis=0)#.iloc[:,0].value_counts()
resp.columns=(['Response'])
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([    
    keras.layers.Dense(512,kernel_initializer='normal', activation='relu',input_shape=[len(train_final.columns)]),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(2)
])

model.summary()

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['mse','mae','accuracy'])
model.fit(train_final1, resp.Response, epochs=35)

#test_loss, test_acc = model.evaluate(X_test,  y_test, verbose=2)

#print('\nTest accuracy:', test_acc)

probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])

predictions = probability_model.predict(test_final)
print(predictions)
preds=predictions[:,1]

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_61 (Dense)             (None, 512)               39936
_________________________________________________________________
dense_62 (Dense)             (None, 256)               131328
_________________________________________________________________
dense_63 (Dense)             (None, 128)               32896
_________________________________________________________________
dense_64 (Dense)             (None, 64)                8256
_________________________________________________________________
dense_65 (Dense)             (None, 32)                2080
_________________________________________________________________
dense_66 (Dense)             (None, 16)                528
_________________________________________________________________
dense_67 (Dense)             (None, 8)                 136
_________________________________________________________________
dense_68 (Dense)             (None, 2)                 18
=================================================================
Total params: 215,178
Trainable params: 215,178
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>
Train on 75300 samples
Epoch 1/35
75300/75300 [==============================] - 6s 84us/sample - loss: 0.6584 - mse: 0.9608 - mae: 0.6701 - accuracy: 0.5938
Epoch 2/35
75300/75300 [==============================] - 6s 77us/sample - loss: 0.6254 - mse: 2.9784 - mae: 0.9456 - accuracy: 0.6302
Epoch 3/35
75300/75300 [==============================] - 6s 80us/sample - loss: 0.6111 - mse: 5.2451 - mae: 1.1575 - accuracy: 0.6412
Epoch 4/35
75300/75300 [==============================] - 6s 82us/sample - loss: 0.5979 - mse: 7.9529 - mae: 1.3577 - accuracy: 0.6540
Epoch 5/35
75300/75300 [==============================] - 7s 91us/sample - loss: 0.5832 - mse: 11.1174 - mae: 1.5223 - accuracy: 0.6658
Epoch 6/35
75300/75300 [==============================] - 6s 80us/sample - loss: 0.5656 - mse: 17.5271 - mae: 1.8363 - accuracy: 0.6795
Epoch 7/35
75300/75300 [==============================] - 6s 80us/sample - loss: 0.5485 - mse: 25.7267 - mae: 2.1366 - accuracy: 0.6938
Epoch 8/35
75300/75300 [==============================] - 6s 81us/sample - loss: 0.5262 - mse: 35.5907 - mae: 2.4514 - accuracy: 0.7122
Epoch 9/35
75300/75300 [==============================] - 6s 83us/sample - loss: 0.5057 - mse: 43.5875 - mae: 2.7396 - accuracy: 0.7275
Epoch 10/35
75300/75300 [==============================] - 6s 82us/sample - loss: 0.4829 - mse: 52.9653 - mae: 3.0124 - accuracy: 0.7440
Epoch 11/35
75300/75300 [==============================] - 6s 79us/sample - loss: 0.4588 - mse: 55.3958 - mae: 3.1746 - accuracy: 0.7613
Epoch 12/35
75300/75300 [==============================] - 6s 81us/sample - loss: 0.4369 - mse: 65.2360 - mae: 3.4455 - accuracy: 0.7771
Epoch 13/35
75300/75300 [==============================] - 6s 75us/sample - loss: 0.4126 - mse: 82.9962 - mae: 3.9126 - accuracy: 0.7923
Epoch 14/35
75300/75300 [==============================] - 5s 73us/sample - loss: 0.3944 - mse: 84.5829 - mae: 4.0247 - accuracy: 0.8029
Epoch 15/35
75300/75300 [==============================] - 6s 78us/sample - loss: 0.3739 - mse: 104.1137 - mae: 4.4734 - accuracy: 0.8167
Epoch 16/35
75300/75300 [==============================] - 6s 80us/sample - loss: 0.3573 - mse: 108.4982 - mae: 4.6330 - accuracy: 0.8257
Epoch 17/35
75300/75300 [==============================] - 6s 78us/sample - loss: 0.3399 - mse: 123.6468 - mae: 4.9430 - accuracy: 0.8353
Epoch 18/35
75300/75300 [==============================] - 5s 71us/sample - loss: 0.3251 - mse: 126.1878 - mae: 5.0968 - accuracy: 0.8439
Epoch 19/35
75300/75300 [==============================] - 6s 79us/sample - loss: 0.3141 - mse: 132.0760 - mae: 5.1839 - accuracy: 0.8518
Epoch 20/35
75300/75300 [==============================] - 6s 83us/sample - loss: 0.2997 - mse: 143.1607 - mae: 5.4851 - accuracy: 0.8597
Epoch 21/35
75300/75300 [==============================] - 6s 77us/sample - loss: 0.2899 - mse: 152.1999 - mae: 5.6923 - accuracy: 0.8654
Epoch 22/35
75300/75300 [==============================] - 6s 78us/sample - loss: 0.2809 - mse: 159.8871 - mae: 5.8639 - accuracy: 0.8704
Epoch 23/35
75300/75300 [==============================] - 6s 77us/sample - loss: 0.2695 - mse: 151.9274 - mae: 5.8962 - accuracy: 0.8748
Epoch 24/35
75300/75300 [==============================] - 6s 75us/sample - loss: 0.2569 - mse: 171.0371 - mae: 6.2945 - accuracy: 0.8825
Epoch 25/35
75300/75300 [==============================] - 5s 71us/sample - loss: 0.2536 - mse: 163.0883 - mae: 6.2120 - accuracy: 0.8852
Epoch 26/35
75300/75300 [==============================] - 5s 73us/sample - loss: 0.2457 - mse: 168.8197 - mae: 6.3677 - accuracy: 0.8899
Epoch 27/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.2348 - mse: 176.5111 - mae: 6.5662 - accuracy: 0.8950
Epoch 28/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.2305 - mse: 154.5286 - mae: 6.3806 - accuracy: 0.8970
Epoch 29/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.2265 - mse: 159.2067 - mae: 6.3949 - accuracy: 0.9004
Epoch 30/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.2193 - mse: 173.8686 - mae: 6.6605 - accuracy: 0.9020
Epoch 31/35
75300/75300 [==============================] - 5s 71us/sample - loss: 0.2124 - mse: 184.1005 - mae: 6.8763 - accuracy: 0.9062
Epoch 32/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.2091 - mse: 152.6243 - mae: 6.5125 - accuracy: 0.9090
Epoch 33/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.2024 - mse: 158.0761 - mae: 6.7218 - accuracy: 0.9107
Epoch 34/35
75300/75300 [==============================] - 5s 72us/sample - loss: 0.1985 - mse: 169.7197 - mae: 6.8868 - accuracy: 0.9130
Epoch 35/35
75300/75300 [==============================] - 6s 82us/sample - loss: 0.1939 - mse: 156.6323 - mae: 6.7494 - accuracy: 0.9160
[[1.2339423e-01 8.7660581e-01]
 [6.8133396e-01 3.1866610e-01]
 [9.9989080e-01 1.0916806e-04]
 ...
 [2.4551203e-02 9.7544879e-01]
 [4.7765426e-02 9.5223463e-01]
 [1.5075627e-03 9.9849248e-01]]

In [106]:
submission=pd.concat([test.ID,pd.DataFrame(preds)],axis=1)
submission.columns=(["ID","Response"])

In [107]:
submission.to_csv("ans.csv",index=False)